/**
 * Generated by Scrooge
 *   version: 4.0.0
 *   rev: 2d9d7656d3b3b7eff89450ac6a78f12af6cc627b
 *   built at: 20150828-134351
 */
package ru.gamover.tagservice.thriftscala

import com.twitter.finagle.{Service, Thrift}
import com.twitter.finagle.stats.{NullStatsReceiver, StatsReceiver}
import com.twitter.scrooge.{ThriftStruct, TReusableMemoryTransport}
import com.twitter.util.Future
import java.nio.ByteBuffer
import java.util.Arrays
import org.apache.thrift.protocol._
import org.apache.thrift.TApplicationException
import org.apache.thrift.transport.TMemoryInputTransport
import scala.collection.mutable.{
  ArrayBuffer => mutable$ArrayBuffer, HashMap => mutable$HashMap}
import scala.collection.{Map, Set}

import scala.language.higherKinds


@javax.annotation.Generated(value = Array("com.twitter.scrooge.Compiler"))
class TagService$FinagleService(
  iface: TagService[Future],
  protocolFactory: TProtocolFactory,
  stats: StatsReceiver,
  maxThriftBufferSize: Int
) extends Service[Array[Byte], Array[Byte]] {
  import TagService._

  def this(
    iface: TagService[Future],
    protocolFactory: TProtocolFactory
  ) = this(iface, protocolFactory, NullStatsReceiver, Thrift.maxThriftBufferSize)


  private[this] val tlReusableBuffer = new ThreadLocal[TReusableMemoryTransport] {
    override def initialValue() = TReusableMemoryTransport(512)
  }

  private[this] def reusableBuffer: TReusableMemoryTransport = {
    val buf = tlReusableBuffer.get()
    buf.reset()
    buf
  }

  private[this] val resetCounter = stats.scope("buffer").counter("resetCount")

  private[this] def resetBuffer(trans: TReusableMemoryTransport): Unit = {
    if (trans.currentCapacity > maxThriftBufferSize) {
      resetCounter.incr()
      tlReusableBuffer.remove()
    }
  }

  protected val functionMap = new mutable$HashMap[String, (TProtocol, Int) => Future[Array[Byte]]]()

  protected def addFunction(name: String, f: (TProtocol, Int) => Future[Array[Byte]]) {
    functionMap(name) = f
  }

  protected def exception(name: String, seqid: Int, code: Int, message: String): Future[Array[Byte]] = {
    try {
      val x = new TApplicationException(code, message)
      val memoryBuffer = reusableBuffer
      try {
        val oprot = protocolFactory.getProtocol(memoryBuffer)

        oprot.writeMessageBegin(new TMessage(name, TMessageType.EXCEPTION, seqid))
        x.write(oprot)
        oprot.writeMessageEnd()
        oprot.getTransport().flush()
        Future.value(Arrays.copyOfRange(memoryBuffer.getArray(), 0, memoryBuffer.length()))
      } finally {
        resetBuffer(memoryBuffer)
      }
    } catch {
      case e: Exception => Future.exception(e)
    }
  }

  protected def reply(name: String, seqid: Int, result: ThriftStruct): Future[Array[Byte]] = {
    try {
      val memoryBuffer = reusableBuffer
      try {
        val oprot = protocolFactory.getProtocol(memoryBuffer)

        oprot.writeMessageBegin(new TMessage(name, TMessageType.REPLY, seqid))
        result.write(oprot)
        oprot.writeMessageEnd()

        Future.value(Arrays.copyOfRange(memoryBuffer.getArray(), 0, memoryBuffer.length()))
      } finally {
        resetBuffer(memoryBuffer)
      }
    } catch {
      case e: Exception => Future.exception(e)
    }
  }

  final def apply(request: Array[Byte]): Future[Array[Byte]] = {
    val inputTransport = new TMemoryInputTransport(request)
    val iprot = protocolFactory.getProtocol(inputTransport)

    try {
      val msg = iprot.readMessageBegin()
      val func = functionMap.get(msg.name)
      func match {
        case _root_.scala.Some(fn) =>
          fn(iprot, msg.seqid)
        case _ =>
          TProtocolUtil.skip(iprot, TType.STRUCT)
          exception(msg.name, msg.seqid, TApplicationException.UNKNOWN_METHOD,
            "Invalid method name: '" + msg.name + "'")
      }
    } catch {
      case e: Exception => Future.exception(e)
    }
  }

  // ---- end boilerplate.

  addFunction("addEntry", { (iprot: TProtocol, seqid: Int) =>
    try {
      val args = AddEntry.Args.decode(iprot)
      iprot.readMessageEnd()
      (try {
        iface.addEntry(args.name)
      } catch {
        case e: Exception => Future.exception(e)
      }) flatMap { value: Long =>
        reply("addEntry", seqid, AddEntry.Result(success = Some(value)))
      } rescue {
        case e => Future.exception(e)
      }
    } catch {
      case e: TProtocolException => {
        iprot.readMessageEnd()
        exception("addEntry", seqid, TApplicationException.PROTOCOL_ERROR, e.getMessage)
      }
      case e: Exception => Future.exception(e)
    }
  })
  addFunction("removeEntry", { (iprot: TProtocol, seqid: Int) =>
    try {
      val args = RemoveEntry.Args.decode(iprot)
      iprot.readMessageEnd()
      (try {
        iface.removeEntry(args.id)
      } catch {
        case e: Exception => Future.exception(e)
      }) flatMap { value: Unit =>
        reply("removeEntry", seqid, RemoveEntry.Result())
      } rescue {
        case e => Future.exception(e)
      }
    } catch {
      case e: TProtocolException => {
        iprot.readMessageEnd()
        exception("removeEntry", seqid, TApplicationException.PROTOCOL_ERROR, e.getMessage)
      }
      case e: Exception => Future.exception(e)
    }
  })
  addFunction("getEntryById", { (iprot: TProtocol, seqid: Int) =>
    try {
      val args = GetEntryById.Args.decode(iprot)
      iprot.readMessageEnd()
      (try {
        iface.getEntryById(args.id)
      } catch {
        case e: Exception => Future.exception(e)
      }) flatMap { value: Seq[ru.gamover.tagservice.thriftscala.Entry] =>
        reply("getEntryById", seqid, GetEntryById.Result(success = Some(value)))
      } rescue {
        case e => Future.exception(e)
      }
    } catch {
      case e: TProtocolException => {
        iprot.readMessageEnd()
        exception("getEntryById", seqid, TApplicationException.PROTOCOL_ERROR, e.getMessage)
      }
      case e: Exception => Future.exception(e)
    }
  })
  addFunction("getEntriesByTags", { (iprot: TProtocol, seqid: Int) =>
    try {
      val args = GetEntriesByTags.Args.decode(iprot)
      iprot.readMessageEnd()
      (try {
        iface.getEntriesByTags(args.tagIdList)
      } catch {
        case e: Exception => Future.exception(e)
      }) flatMap { value: Seq[ru.gamover.tagservice.thriftscala.Entry] =>
        reply("getEntriesByTags", seqid, GetEntriesByTags.Result(success = Some(value)))
      } rescue {
        case e => Future.exception(e)
      }
    } catch {
      case e: TProtocolException => {
        iprot.readMessageEnd()
        exception("getEntriesByTags", seqid, TApplicationException.PROTOCOL_ERROR, e.getMessage)
      }
      case e: Exception => Future.exception(e)
    }
  })
  addFunction("addTag", { (iprot: TProtocol, seqid: Int) =>
    try {
      val args = AddTag.Args.decode(iprot)
      iprot.readMessageEnd()
      (try {
        iface.addTag(args.name)
      } catch {
        case e: Exception => Future.exception(e)
      }) flatMap { value: Long =>
        reply("addTag", seqid, AddTag.Result(success = Some(value)))
      } rescue {
        case e => Future.exception(e)
      }
    } catch {
      case e: TProtocolException => {
        iprot.readMessageEnd()
        exception("addTag", seqid, TApplicationException.PROTOCOL_ERROR, e.getMessage)
      }
      case e: Exception => Future.exception(e)
    }
  })
  addFunction("removeTag", { (iprot: TProtocol, seqid: Int) =>
    try {
      val args = RemoveTag.Args.decode(iprot)
      iprot.readMessageEnd()
      (try {
        iface.removeTag(args.id)
      } catch {
        case e: Exception => Future.exception(e)
      }) flatMap { value: Unit =>
        reply("removeTag", seqid, RemoveTag.Result())
      } rescue {
        case e => Future.exception(e)
      }
    } catch {
      case e: TProtocolException => {
        iprot.readMessageEnd()
        exception("removeTag", seqid, TApplicationException.PROTOCOL_ERROR, e.getMessage)
      }
      case e: Exception => Future.exception(e)
    }
  })
  addFunction("getTagById", { (iprot: TProtocol, seqid: Int) =>
    try {
      val args = GetTagById.Args.decode(iprot)
      iprot.readMessageEnd()
      (try {
        iface.getTagById(args.id)
      } catch {
        case e: Exception => Future.exception(e)
      }) flatMap { value: Seq[ru.gamover.tagservice.thriftscala.Tag] =>
        reply("getTagById", seqid, GetTagById.Result(success = Some(value)))
      } rescue {
        case e => Future.exception(e)
      }
    } catch {
      case e: TProtocolException => {
        iprot.readMessageEnd()
        exception("getTagById", seqid, TApplicationException.PROTOCOL_ERROR, e.getMessage)
      }
      case e: Exception => Future.exception(e)
    }
  })
  addFunction("getEntryTags", { (iprot: TProtocol, seqid: Int) =>
    try {
      val args = GetEntryTags.Args.decode(iprot)
      iprot.readMessageEnd()
      (try {
        iface.getEntryTags(args.entryId)
      } catch {
        case e: Exception => Future.exception(e)
      }) flatMap { value: Seq[ru.gamover.tagservice.thriftscala.Tag] =>
        reply("getEntryTags", seqid, GetEntryTags.Result(success = Some(value)))
      } rescue {
        case e => Future.exception(e)
      }
    } catch {
      case e: TProtocolException => {
        iprot.readMessageEnd()
        exception("getEntryTags", seqid, TApplicationException.PROTOCOL_ERROR, e.getMessage)
      }
      case e: Exception => Future.exception(e)
    }
  })
  addFunction("addTagToEntry", { (iprot: TProtocol, seqid: Int) =>
    try {
      val args = AddTagToEntry.Args.decode(iprot)
      iprot.readMessageEnd()
      (try {
        iface.addTagToEntry(args.entryId, args.tagId)
      } catch {
        case e: Exception => Future.exception(e)
      }) flatMap { value: Long =>
        reply("addTagToEntry", seqid, AddTagToEntry.Result(success = Some(value)))
      } rescue {
        case e => Future.exception(e)
      }
    } catch {
      case e: TProtocolException => {
        iprot.readMessageEnd()
        exception("addTagToEntry", seqid, TApplicationException.PROTOCOL_ERROR, e.getMessage)
      }
      case e: Exception => Future.exception(e)
    }
  })
  addFunction("removeTagFromEntry", { (iprot: TProtocol, seqid: Int) =>
    try {
      val args = RemoveTagFromEntry.Args.decode(iprot)
      iprot.readMessageEnd()
      (try {
        iface.removeTagFromEntry(args.entryId, args.tagId)
      } catch {
        case e: Exception => Future.exception(e)
      }) flatMap { value: Unit =>
        reply("removeTagFromEntry", seqid, RemoveTagFromEntry.Result())
      } rescue {
        case e => Future.exception(e)
      }
    } catch {
      case e: TProtocolException => {
        iprot.readMessageEnd()
        exception("removeTagFromEntry", seqid, TApplicationException.PROTOCOL_ERROR, e.getMessage)
      }
      case e: Exception => Future.exception(e)
    }
  })
}